### ISSUE TITLE
stringmorph disappears when it loses focus

### ISSUE THREAD

**Issue by kilon** [kilon/pyEphestos#1]
stringmorph seems to disappear when it loses focus , and reappears when mouse enters and gains focus. Its also painted black and not the regular color. 

one of these commits may affected the bug 

https://github.com/kilon/Ephestos/commit/55d5f35c609841a2f002c0ddf83c0890971c3353

https://github.com/kilon/Ephestos/commit/c865cbf26a31e9193dd783b64a061e83f10d27fd

**Comment by PKHG** [comment]
at 29 jun the activation indicator stays visible red if mouse is outside the input, green if active.

**Comment by kilon** [comment]
yes but the text in stringfield should display even when the mouse is outside it , and when the mouse leave it become invisible

**Comment by PKHG** [comment]
reason was a missing super(...).draw() ;-)
pushed https://github.com/kilon/Ephestos/commit/f5998705b83ad493c7758bdf99b0c7f7b8f58a31
