### ISSUE TITLE
The importance of pyglet for Ephestos

### ISSUE THREAD

**Issue by kilon** [kilon/pyEphestos#5]
Pyglet is necessary, for 3 reasons 

1) to borrow code regarding several areas that pyglet already addresses 

2) to make a standalone version for Ephestos for cpython 3.2 and pypy that will work in all OS and still be 100% pure python

3) in case bgl fails and is proven very buggy, then we can still keep Ephestos standalone but instead of embedding it inside blender window make a separate window for it using pyglet. 

Option 3 is particular appealing to me because even though we lose the big advantage of having Ephestos and bender on the same window on the other hand Unlike bgl , pyglet is not limited to opengl 1.1 , it can use any kind of opengl even opengl 4 . That could mean for us , great speed up in displaying Morpheas , plus a huge array of graphical abilities and an access to all the latest opengl technology and libraries. The fact that PKHG has bee able to make pyglet partially running with python 3 and the fact that pyglet developer are moving towards a full python 3 version plus the fact that pyglet already run in pypy which can greatly speed up python makes pyglet a great candidate for us.

In addition to that there are many pyglet libraries out there we can use , an example is pyprocessing , a port of the very popular Processling library (Java) to python. 

Use this thread to discuss ideas, offer advice etc. This thread is open to Ephestos developers and Ephestos users

**Comment by PKHG** [comment]
YES if pyglet with python 2.7 could be persuaded to use Ephestos? Please, Kilon, try and explain to do part 3)

**Comment by kilon** [comment]
well the best scenario i can think right now if and only if bgl proves a non viable solution for us , because of too many bugs is to call pyglet from pypy and the addon to only communicate data to main ephestos application in pypy. This is already possible because of my bridge and because we dont need to port pyglet to python 3. Of course that will mean a separate window for morpheas which I am trying to avoid. Bretth has suggested to me the Ghost API which is the API where the blender gui is based on, the good thing about it is that it uses ctypes and it could be possible to use pyglet to render it so make it easier for use to embed morpheas inside blender. But I am not so convinced Ghost API will work with no serious bugs. 

Running Ephesto from pypy also means a big boost in python speed which will be a big plus for any developer wanting to use Ephestos. 

The only disadvantages I see is :
a) we lose the ability to embed morpheas inside blender
b) many python libraries do not work in pypy

b is not such a problem because those libraries can be called from blender python and then communicate via the bridge with pypy , a is my only concern.
